// <auto-generated />
namespace Park.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editledAndCarmers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editledAndCarmers));
        
        string IMigrationMetadata.Id
        {
            get { return "201809090837195_edit ledAndCarmers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
